name: music_player
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  just_audio: ^0.9.40
  audio_service: ^0.18.11
  audio_session: ^0.1.18
  path_provider: ^2.1.1
  provider: ^6.1.1
  geolocator: ^13.0.1
  google_fonts: ^6.2.1
  flutter_blurhash: ^0.7.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - music_list.json
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/pink_player_icon.png"
  adaptive_icon_background: "#2E003E"
  adaptive_icon_foreground: "assets/icon/pink_player_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#000000"
  background_image: "assets/splash/pink_gradient_bg.png"
  image: "assets/icon/pink_player_icon.png"
  android_12:
    color: "#000000"
    image: "assets/icon/pink_player_icon.png"
  android: true
  ios: true
  web: true
